doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: false
        mappings:
            Product:
                is_bundle: false
                type: yml
                dir: '%kernel.project_dir%/src/Infrastructure/Doctrine/Mapping'
                prefix: App\Domain\Product
                alias: AppDomainProduct
            ProductValueObject:
                is_bundle: false
                type: yml
                dir: '%kernel.project_dir%/src/Infrastructure/Doctrine/Mapping/ValueObject'
                prefix: App\Domain\Product\ValueObject
                alias: AppDomainProductValueObject