#controllers:
#    resource: ../../src/Controller/
#    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation

controllers:
    resource: '../../src/Infrastructure/Symfony/Controller/'
    type: annotation